{
 "title": "PANEL DE PROCESOS EN EL SISTEMA",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "PANEL DE CONTENEDORES POR #202041390",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "SELECT mem_total_kb / 1024.0 / 1024.0 AS \"TOTAL DE RAM\"\nFROM sys_metrics\nORDER BY ts DESC\nLIMIT 1;",
       "rawQueryText": "SELECT mem_total_kb / 1024.0 / 1024.0 AS \"TOTAL DE RAM\"\nFROM sys_metrics\nORDER BY ts DESC\nLIMIT 1;",
       "timeColumns": [
        "time",
        "ts"
       ]
      },
      {
       "queryText": "SELECT mem_free_kb / 1024.0 / 1024.0 AS \"MEMORIA RAM LIBRE\"\nFROM sys_metrics\nORDER BY ts DESC\nLIMIT 1;",
       "rawQueryText": "SELECT mem_free_kb / 1024.0 / 1024.0 AS \"MEMORIA RAM LIBRE\"\nFROM sys_metrics\nORDER BY ts DESC\nLIMIT 1;",
       "timeColumns": [
        "time",
        "ts"
       ]
      },
      {
       "queryText": "SELECT COUNT(*) AS \"TOTAL DE CONTENEDORES ELIMINADOS\"\nFROM deletions;",
       "rawQueryText": "SELECT COUNT(*) AS \"TOTAL DE CONTENEDORES ELIMINADOS\"\nFROM deletions;",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "USO DE RAM EN EL TIEMPO",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "queryText": "SELECT \n  ts * 1000 AS time,\n  mem_used_kb / 1024.0 / 1024.0 AS \"USO DE RAM EN EL TIEMPO\"\nFROM sys_metrics\nORDER BY ts ASC;",
       "rawQueryText": "SELECT \n  ts * 1000 AS time,\n  mem_used_kb / 1024.0 / 1024.0 AS \"USO DE RAM EN EL TIEMPO\"\nFROM sys_metrics\nORDER BY ts ASC;",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "TOP 5 +CPU",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "SELECT\n  container_id,\n  image,\n  pid,\n  mem_pct,\n  cpu_pct,\n  datetime(ts, 'unixepoch') AS timestamp\nFROM containers\nWHERE container_id IS NOT NULL AND container_id != ''\nORDER BY mem_pct DESC\nLIMIT 5;",
       "rawQueryText": "SELECT\n  container_id,\n  image,\n  pid,\n  mem_pct,\n  cpu_pct,\n  datetime(ts, 'unixepoch') AS timestamp\nFROM containers\nWHERE container_id IS NOT NULL AND container_id != ''\nORDER BY mem_pct DESC\nLIMIT 5;",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "TOP 5 +RAM",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 9, "x": 8, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "SELECT\n  container_id,\n  image,\n  pid,\n  cpu_pct,\n  mem_pct,\n  datetime(ts, 'unixepoch') AS timestamp\nFROM containers\nWHERE container_id IS NOT NULL AND container_id != ''\nORDER BY cpu_pct DESC\nLIMIT 5;",
       "rawQueryText": "SELECT\n  container_id,\n  image,\n  pid,\n  cpu_pct,\n  mem_pct,\n  datetime(ts, 'unixepoch') AS timestamp\nFROM containers\nWHERE container_id IS NOT NULL AND container_id != ''\nORDER BY cpu_pct DESC\nLIMIT 5;",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "MEMORIA RAM USADA",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 7, "x": 17, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "SELECT mem_used_kb / 1024.0 / 1024.0 AS \"MEMORIA RAM USADA\"\nFROM sys_metrics\nORDER BY ts DESC\nLIMIT 1;",
       "rawQueryText": "SELECT mem_used_kb / 1024.0 / 1024.0 AS \"MEMORIA RAM USADA\"\nFROM sys_metrics\nORDER BY ts DESC\nLIMIT 1;",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "PANEL DE PROCESOS EN EL SISTEMA POR #202041390",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "SELECT mem_total_kb / 1024.0 / 1024.0 AS \"TOTAL DE RAM\"\nFROM sys_metrics\nORDER BY ts DESC\nLIMIT 1;\n",
       "rawQueryText": "SELECT mem_total_kb / 1024.0 / 1024.0 AS \"TOTAL DE RAM\"\nFROM sys_metrics\nORDER BY ts DESC\nLIMIT 1;\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      },
      {
       "queryText": "SELECT mem_free_kb / 1024.0 / 1024.0 AS \"MEMORIA RAM LIBRE\"\nFROM sys_metrics\nORDER BY ts DESC\nLIMIT 1;\n",
       "rawQueryText": "SELECT mem_free_kb / 1024.0 / 1024.0 AS \"MEMORIA RAM LIBRE\"\nFROM sys_metrics\nORDER BY ts DESC\nLIMIT 1;\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      },
      {
       "queryText": "SELECT total AS \"TOTAL DE PROCESOS CONTADOS\"\nFROM process_count\nORDER BY ts DESC\nLIMIT 1;\n",
       "rawQueryText": "SELECT total AS \"TOTAL DE PROCESOS CONTADOS\"\nFROM process_count\nORDER BY ts DESC\nLIMIT 1;\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "USO DE RAM EN EL TIEMPO",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "queryText": "SELECT \n  ts * 1000 AS time,\n  mem_used_kb / 1024.0 / 1024.0 AS \"USO DE RAM EN EL TIEMPO\"\nFROM sys_metrics\nORDER BY ts ASC;\n",
       "rawQueryText": "SELECT \n  ts * 1000 AS time,\n  mem_used_kb / 1024.0 / 1024.0 AS \"USO DE RAM EN EL TIEMPO\"\nFROM sys_metrics\nORDER BY ts ASC;\n",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "TOP 5 +CPU",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "SELECT\n  pid,\n  image AS process_name,\n  mem_pct,\n  cpu_pct,\n  datetime(ts, 'unixepoch') AS timestamp\nFROM containers\nWHERE container_id = '' OR container_id IS NULL\nORDER BY mem_pct DESC\nLIMIT 5;",
       "rawQueryText": "SELECT\n  pid,\n  image AS process_name,\n  mem_pct,\n  cpu_pct,\n  datetime(ts, 'unixepoch') AS timestamp\nFROM containers\nWHERE container_id = '' OR container_id IS NULL\nORDER BY mem_pct DESC\nLIMIT 5;",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "TOP 5 +RAM",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 10, "x": 9, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "SELECT\n  pid,\n  image AS process_name,\n  cpu_pct,\n  mem_pct,\n  datetime(ts, 'unixepoch') AS timestamp\nFROM containers\nWHERE container_id = '' OR container_id IS NULL\nORDER BY cpu_pct DESC\nLIMIT 5;",
       "rawQueryText": "SELECT\n  pid,\n  image AS process_name,\n  cpu_pct,\n  mem_pct,\n  datetime(ts, 'unixepoch') AS timestamp\nFROM containers\nWHERE container_id = '' OR container_id IS NULL\nORDER BY cpu_pct DESC\nLIMIT 5;",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    },
    {
     "title": "MEMORIA RAM USADA",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "queryText": "SELECT mem_used_kb / 1024.0 / 1024.0 AS \"MEMORIA RAM USADA\"\nFROM sys_metrics\nORDER BY ts DESC\nLIMIT 1;",
       "rawQueryText": "SELECT mem_used_kb / 1024.0 / 1024.0 AS \"MEMORIA RAM USADA\"\nFROM sys_metrics\nORDER BY ts DESC\nLIMIT 1;",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  }
 ]
}